services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestiontelecom-app
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - db

  webserver:
    image: nginx:latest
    container_name: gestiontelecom-webserver
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: postgres:10
    container_name: gestiontelecom-db
    environment:
      POSTGRES_DB: telecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
