services:
  web:
    image: app-name:latest
    build:
      target: web
      context: .
    env_file:
      - .env_docker
    ports:
      - "8181:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage
      /var/www/html/bootstrap/cache &&
      chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
      php-fpm"

  db:
    image: postgres:10
    container_name: gestiontelecom-db
    environment:
      POSTGRES_DB: telecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: