services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestiontelecom-app
    ports:
      - "5050:9000"
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules 
    networks:
      - laravel
    depends_on:
      - db
    env_file:
      - .env_docker
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
             chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
             php-fpm"

  webserver:
    image: nginx:latest
    container_name: gestiontelecom-webserver
    ports:
      - "8181:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: postgres:10
    container_name: gestiontelecom-db
    environment:
      POSTGRES_DB: telecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
